# Generated by Django 4.0.3 on 2022-05-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('alarme_bit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.alarme')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('alarme_padrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarme_padrao', to='core.alarme')),
                ('bit_padrao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bit_padrao', to='core.bit')),
            ],
        ),
    ]
