# Generated by Django 4.0.3 on 2022-05-17 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bit',
            name='alarme_bit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.alarme'),
        ),
    ]
