# Generated by Django 4.0.3 on 2022-05-17 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bit_alarme_bit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='alarme_padrao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarme_padrao', to='core.alarme'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='bit_padrao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bit_padrao', to='core.bit'),
        ),
    ]
