# Generated by Django 4.0.3 on 2022-05-17 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_objeto_alarme_padrao_remove_objeto_bit_padrao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarme',
            name='alarme_padrao',
        ),
        migrations.RemoveField(
            model_name='bit',
            name='bit_padrao',
        ),
        migrations.AddField(
            model_name='alarme',
            name='alarme_objeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alarme_objeto', to='core.objeto'),
        ),
        migrations.AddField(
            model_name='bit',
            name='bit_objeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bit_objeto', to='core.objeto'),
        ),
    ]
