# Generated by Django 4.0.3 on 2022-05-17 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_alarme_alarme_padrao_remove_bit_bit_padrao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bit',
            name='alarme_bit',
        ),
        migrations.AddField(
            model_name='alarme',
            name='alarme_bit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bit'),
        ),
    ]
