# Generated by Django 4.0.3 on 2022-05-18 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_bit_alarme_bit_alarme_alarme_bit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfg', models.CharField(max_length=50)),
                ('input_tag', models.CharField(max_length=50, verbose_name='Input Tag')),
                ('condition', models.CharField(choices=[(0, 0), (1, 1)], max_length=50, verbose_name='Condition')),
                ('latched', models.BooleanField(verbose_name='Latched')),
                ('ack_required', models.BooleanField(verbose_name='Acknowledge required')),
                ('show_alarm', models.BooleanField(verbose_name='Show Alarm as a Tag')),
                ('minimum_duration', models.DecimalField(decimal_places=2, max_digits=8)),
                ('alarm_class', models.CharField(max_length=50, verbose_name='Alarm Class')),
                ('factory', models.CharField(max_length=100, verbose_name='Factory Talk View Command')),
                ('alarme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Severity', to='core.alarme')),
            ],
        ),
    ]
