# Generated by Django 4.0.3 on 2022-05-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_configuracao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracao',
            options={'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações'},
        ),
    ]
