# Generated by Django 4.0.3 on 2022-05-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_configuracao_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='cfg',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
