# Generated by Django 4.0.3 on 2022-05-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_configuracao_cfg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='latched',
        ),
    ]
