# Generated by Django 4.0.3 on 2022-05-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_configuracao_ack_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='cfg',
            field=models.CharField(max_length=50),
        ),
    ]
