# Generated by Django 4.0.3 on 2022-05-18 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_configuracao_cfg'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='alarm_class',
            field=models.CharField(max_length=50, null=True, verbose_name='Alarm Class'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='alarme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Severity', to='core.alarme'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='condition',
            field=models.CharField(choices=[('0', 0), ('1', 1)], max_length=50, null=True, verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='factory',
            field=models.CharField(max_length=100, null=True, verbose_name='Factory Talk View Command'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='input_tag',
            field=models.CharField(max_length=50, null=True, verbose_name='Input Tag'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='latched',
            field=models.BooleanField(null=True, verbose_name='Latched'),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='minimum_duration',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='configuracao',
            name='show_alarm',
            field=models.BooleanField(null=True, verbose_name='Show Alarm as a Tag'),
        ),
    ]
