# Generated by Django 4.0.3 on 2022-05-18 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_configuracao_alarm_class_configuracao_alarme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='alarm_class',
            field=models.CharField(default=1, max_length=50, verbose_name='Alarm Class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='alarme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Severity', to='core.alarme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='condition',
            field=models.CharField(choices=[('0', 0), ('1', 1)], default=1, max_length=50, verbose_name='Condition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='factory',
            field=models.CharField(default=1, max_length=100, verbose_name='Factory Talk View Command'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='input_tag',
            field=models.CharField(default=1, max_length=50, verbose_name='Input Tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='latched',
            field=models.BooleanField(default=1, verbose_name='Latched'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='minimum_duration',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracao',
            name='show_alarm',
            field=models.BooleanField(default=1, verbose_name='Show Alarm as a Tag'),
            preserve_default=False,
        ),
    ]
