# Generated by Django 4.0.3 on 2022-05-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_configuracao_alarm_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='ak_required',
            field=models.BooleanField(default=1, verbose_name='Acknowledge required'),
            preserve_default=False,
        ),
    ]
