# Generated by Django 4.0.3 on 2022-05-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_configuracao_ak_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='severity',
            field=models.CharField(default=1, max_length=50, verbose_name='Severity'),
            preserve_default=False,
        ),
    ]
