# Generated by Django 4.0.3 on 2022-05-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_configuracao_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracao',
            name='cfg',
        ),
    ]
