# Generated by Django 4.0.3 on 2022-05-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_input tag (bit)_configuracao_input_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='input_tag',
            field=models.CharField(max_length=100, verbose_name='input_tag(bit)'),
        ),
    ]
